name: core_project
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter












  #---------------CORE LIBRARY---------------
  #state management
  flutter_mobx: ^2.0.6+5
  mobx: ^2.1.3
  mobx_codegen:
  get_it: ^7.2.0
  #localization
  intl: 
  #network
  dio:
  #ui
  google_fonts:
  cached_network_image: 
  octo_image: 
  flutter_svg: 
  #storage
  shared_preferences:
  #utilities
  connectivity_plus:
  permission_handler: 
  image_picker:
  app_settings:
  image_cropper:
  flutter_local_notifications:
  #logger
  sentry_flutter:
  #custom
  native_widgets:
    git:
      url: https://github.com/sinanhaci/native_widgets.git
      ref: main
  custom_image_viewer:
    git:
      url: https://github.com/sinanhaci/custom_image_viewer.git
      ref: main


 
  
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.2.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/

